### ISSUE TITLE
Support multiple AI providers (and an OSS option)

### ISSUE THREAD

**Issue by nichochar** [srcbookdev/srcbook#161]
Today, we support only 1 provider: openAI.

In the settings, users should be able to pick between:

* OpenAI (they need to specify an API key)
* Anthropic Claude (they need to specify an API key)
* Ollama (they need to specify a url)

We need a UX pattern where they can select which of the AI providers they want, which also makes it clear if AI is enabled or not (at least one API key is provided and that provider is selected).

Not sure yet if we want to use an abstraction like Ollama or LMStudio for people picking their own model, vs a "openAI compatible API url".

**Comment by swk777** [comment]
how about developing a plugin system where each plugin is essentially a srcbook? This way, secrets can be used for configuration.
