### ISSUE TITLE
Entering an invalid letter may crash a srcbook and prevent it from further changes

### ISSUE THREAD

**Issue by zenyr** [srcbookdev/srcbook#192]
- Version: `srcbook@0.0.1-alpha.16` via `npx srcbook start` OR `bun x srcbook start` (essentially the same, using Node 22)
- OS: `OSX 14.4.1`

# How to reproduce the issue
1. Create an empty srcbook
2. Create a typescript block
3. Press Shift+Option+F OR copy & paste to insert `Ï` in anywhere
4. srcbook immediately crashes
5. restarting srcbook server works BUT opening aforementioned srcbook will immediately crash again
    - You CAN delete the srcbook but it is difficult to recover its contents

| Screenshot in question |
|:-----------------------:|
| <img width="749" alt="image" src="https://github.com/user-attachments/assets/1cff59b1-a58b-4711-bb64-faadc0704344"> |

**Comment by benjreinhart** [comment]
Interesting, will take a look at fixing this asap. Thanks for reporting!
