### ISSUE TITLE
"Getting Started" missing package.json

### ISSUE THREAD

**Issue by avimar** [srcbookdev/srcbook#193]
Hi from hackernews!
Super weird. I tried the "getting started" example, but it has a toast: "Packages need to be installed"

The packge.json file is missing. It's in the code https://github.com/srcbookdev/srcbook/blob/main/packages/api/srcbook/examples/getting-started.src.md

but not in my npm install. Inside node_modules there's no examples folder, so not sure where it's even getting everything else from. compiled rollup before it was fixed?

How do I even manually add a `package.json`? when I do js, then type in package.json, it says invalid file name.

p.s. the AI integration seems fantastic. I said to use the previous cell's info and it accurately imported it without me specifying the name!

**Comment by benjreinhart** [comment]
Hey @avimar, you're pointing out something we need to do better on! The package.json is behind the srcbook settings drawer, which is non-obvious at first. As for the toast, that's telling you that you should run npm install and if you click the `install` button on the toast that's what it'll do.

There are also keyboard shortcuts to open this settings drawer (`⌘` `;`) and package install modal to select and install a single package (`⌘` `i`).

<img width="1424" alt="Screenshot 2024-08-21 at 10 55 55 AM" src="https://github.com/user-attachments/assets/47c2e0c3-3007-4746-b01f-639c87d689ad">

<img width="1424" alt="Screenshot 2024-08-21 at 10 56 02 AM" src="https://github.com/user-attachments/assets/82272bd8-2402-47c5-b98c-50995adf41db">

**Comment by avimar** [comment]
![image](https://github.com/user-attachments/assets/5cdb9219-8c98-45dd-aa3a-10bb488b4efb)

OK, it shows me to install, but once I click, it still gives an error when I run it again.


I see it in settings now -- doesn't seem like it should be hidden away.
But when I click `npm install` it just flashes. It doesn't install. I don't see anything in chrome console or network. The CLI that I ran `npx srcbook start` doesn't show any errors or information.

This is on two different windows 10 machines.
