### ISSUE TITLE
Contact & Feedback

### ISSUE THREAD

**Issue by baruchiro** [srcbookdev/srcbook#198]
Where do I leave my feedback?

Would you like to open the option for Github Discussion? Or a discord server?

**Comment by jaypee15** [comment]
I would like this too

**Comment by benjreinhart** [comment]
We have [a discord](https://discord.gg/shDEGBSe2d) and I just opened discussions up. For now I'd say if you think it's something that would be a good discussion for others to participate in, then discussions are probably best.

Appreciate any/all feedback 🙏🏻
