### ISSUE TITLE
how is this different from something like Observable

### ISSUE THREAD

**Issue by heaversm** [srcbookdev/srcbook#199]
Aside from typescript support, can you give me a sense of how srcbook differentiates itself from [Observable](https://observablehq.com/documentation/notebooks/)?

**Comment by benjreinhart** [comment]
Good question. We've gotten this (and others a few times) and realized that we need to add this somewhere so I created a FAQ.

https://github.com/srcbookdev/srcbook/blob/main/FAQ.md#how-is-srcbook-different-from-observable

Please let us know if anything there is inaccurate
