### ISSUE TITLE
Cap title length of srcbooks

### ISSUE THREAD

**Issue by nichochar** [srcbookdev/srcbook#207]
### Objective
Limit Srcbook titles (encoded as markdown h1) to a maximum length for design and pragmatic reasons.

### Requirements
1. Set max title length to N characters (proposed: N = ~~50~~ 44)
2. Implement validation at:
   - Import time
   - Client-side update in /srcbook view
   - Server-side update

**Comment by benjreinhart** [comment]
We already have one area that caps this at 44 characters. I believe that was calculated based on the available space in the cards on the home page and also how it looks visually on the Srcbook page.
