### ISSUE TITLE
Cannot override files when exporting

### ISSUE THREAD

**Issue by nichochar** [srcbookdev/srcbook#229]
When exporting a `*.src.md` file, if the user wants to overwrite a file which already exists, we currently prevent it and the server prints the following error:

```
Error: Cannot export .src.md file: /Users/nicholascharriere/sourcebooks/sdk.src.md already exists
```

I think we should change this behavior. Both of these would be better:
- simplify override and erase the file
- add a warning with the ability to cancel or overwrite

**Comment by benjreinhart** [comment]
> add a warning with the ability to cancel or overwrite

If we keep this export functionality, then this is my vote (silent overwrites could be bad).

However, we did also talk about removing our modal and using the default browser / os one in which case we'd remove this functionality and it'd be replaced with the native file picker.

**Comment by Aswanth-c** [comment]
> > add a warning with the ability to cancel or overwrite
> 
> If we keep this export functionality, then this is my vote (silent overwrites could be bad).
> 
> However, we did also talk about removing our modal and using the default browser / os one in which case we'd remove this functionality and it'd be replaced with the native file picker.

We have migrated  to using native filer picker so this issue can be closed

**Comment by Sanjoy-droid** [comment]
@nichochar is this issue solved by now?

**Comment by benjreinhart** [comment]
Yes i believe it is now that we changed to use the browser's file exporting.
