### ISSUE TITLE
The srcbook cannot refresh when the local file is modified unless the service is restarted

### ISSUE THREAD

**Issue by swk777** [srcbookdev/srcbook#233]
Can the local file be reloaded when the page refreshes, or add a refresh button on the page?

**Comment by benjreinhart** [comment]
We can do this and probably will at some point, but for now it's not expected that users are manually editing the files in the srcbook's directory. We've been treating that directory as a private implementation detail. This abstraction is not sound though, and maybe we need to start exposing it directly to users at which point we would absolutely need to do this.

What is your use case?
