### ISSUE TITLE
Auto-install deps when creating a new TypeScript Srcbook

### ISSUE THREAD

**Issue by nichochar** [srcbookdev/srcbook#249]
Currently, when you create a new TypeScript Srcbook, you are prompted to manually install deps through the modal:
![CleanShot 2024-09-03 at 19 41 23](https://github.com/user-attachments/assets/41e272e2-c7c1-47a5-a850-d268decc7bbd)

The deps (see screenshot below) need to be installed before any cell can be run. There's no huge security risk since these are default packages that we hardcode into the app, and they are being installed into a new, clean directory.
![CleanShot 2024-09-03 at 19 41 29](https://github.com/user-attachments/assets/424d0f62-64d4-4252-8cc5-eceedeb0f8d5)

Therefore, we should simply auto-install them.

The only consideration is a future one: in the future we might want to open Srcbooks "within a directory", and that directory might already have a package.json and node_modules/. That being said, premature optimization is the root of all badness so we can mostly ignore this, unless there are some obvious wins to prepare for it as the auto-install is written.

**Comment by benjreinhart** [comment]
This is a duplicate of https://github.com/srcbookdev/srcbook/issues/210, can you close one?

**Comment by nichochar** [comment]
Yeah, closing this one. Dupe of #210
