### ISSUE TITLE
Empty tooltips should not be rendered

### ISSUE THREAD

**Issue by benjreinhart** [srcbookdev/srcbook#254]
Noticed while hovering over a comment that we render an empty tooltip. There may be other cases where this happens.

<img width="267" alt="Screenshot 2024-09-05 at 11 20 01 AM" src="https://github.com/user-attachments/assets/53cf83e4-30fb-4ac4-ac5d-31c890c83384">

**Comment by versecafe** [comment]
Fixed in #259
