### ISSUE TITLE
Secrets panel on Srcbook page improvements

### ISSUE THREAD

**Issue by benjreinhart** [srcbookdev/srcbook#295]
Some simple improvements to secrets panel that would be nice:

1. Better 'empty state' experience
2. Support for adding new secrets inline

We will get some designs but in the meantime simple is better.

**Comment by Sanjoy-droid** [comment]
@benjreinhart  I have made some improvements could you please review? and if any modifications you want  do let me know

**Comment by benjreinhart** [comment]
Sorry for the confusion here but #310 should have closed this for now.
