### ISSUE TITLE
Uncaught exception - Session with id "not found" after deleting an scrbook

### ISSUE THREAD

**Issue by BeRecursive22** [srcbookdev/srcbook#299]
Steps to reproduce:

1. Create a new TS srcbook
2. Install the dependencies and hit "Generate SrcBook"
3. Feed the prompt and generate the code and run it.
4. Now "Delete" the srcbook.
5. You'll be able to see requests failing in the network tab.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/01f3d00c-2acc-4903-89d4-1d2c14b4b142">

6. The server crashed due to unhandled exception of "Session not found" error
<img width="978" alt="image" src="https://github.com/user-attachments/assets/32fc504e-360c-4d3e-85d0-eeaa601122fe">

Steps to fix it:

1. remove redundant removal of srcbook's directory leading the uncaught exception
2. Steps to reproduce:

1. Create a new TS srcbook
2. Install the dependencies and hit "Generate SrcBook"
3. Feed the prompt and generate the code and run it.
4. Now "Delete" the srcbook.
5. You'll be able to see requests failing in the network tab.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/01f3d00c-2acc-4903-89d4-1d2c14b4b142">

6. The server crashed due to unhandled exception of "Session not found" error
<img width="978" alt="image" src="https://github.com/user-attachments/assets/32fc504e-360c-4d3e-85d0-eeaa601122fe">

Steps to fix it:

1. remove the redundant removal of the directory causing unhandled exception error
<img width="586" alt="image" src="https://github.com/user-attachments/assets/432045a0-b039-4d40-bed9-ea32be99b24b">
2. deleteSessionByDirname could not find the session with dirname since it was already deleted in the previous step.

**Comment by BeRecursive22** [comment]
@nichochar I would like to work on it.

**Comment by Lokendra-sinh** [comment]
@benjreinhart Hey... just wanted to check if you were able to reproduce this?

**Comment by nichochar** [comment]
> @nichochar I would like to work on it.

Hey @BeRecursive22 , happy for you to take a stab. I'll assign it to you for now.

**Comment by BeRecursive22** [comment]
@nichochar https://github.com/srcbookdev/srcbook/pull/313 for your reference.

**Comment by Sanjoy-droid** [comment]
@BeRecursive22 @nichochar is this issue fixed yet?

**Comment by BeRecursive22** [comment]
@Sanjoy-droid its completed. Thanks mate
