### ISSUE TITLE
Stopping the cell crashes the server with uncaught error

### ISSUE THREAD

**Issue by BeRecursive22** [srcbookdev/srcbook#323]
Steps to reproduce:

- Write/generate Typescript code and run it
- Stop the cell from running
- result is server crash

[screen-capture (17).webm](https://github.com/user-attachments/assets/b722e286-7c0c-424a-a484-45cff170c2b9)

Result:

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/8c44d5dc-0bc8-423b-a5a0-f1bef17cdf05">

**Comment by BeRecursive22** [comment]
@benjreinhart @nichochar just adding try...catch will do the trick I believe. Let me know if you want me to open a PR for this?
```const killed = processes.kill(session.id, cell.id);```

**Comment by Lokendra-sinh** [comment]
hey @nichochar , did you get a chance to reproduce this?

**Comment by BeRecursive22** [comment]
#334
